export const DataArticles = [
  {
    id: 5,
    images: [
      { src: "cityzen/video1.mp4", type: "video" },
      { src: "cityzen/video2.mp4", type: "video" },
      { src: "cityzen/image1.png" },
      { src: "cityzen/image2.png" },
      { src: "cityzen/image3.png" },
      { src: "cityzen/image4.png" },
      { src: "cityzen/image5.png" },
      { src: "cityzen/image7.png" },
      { src: "cityzen/image8.png" },
      { src: "cityzen/image6.png" },
      { src: "cityzen/image9.png" },
    ],
    year: 2023,
    type: "Auto-Entrepreneur",
    role: "Full-Stack - Vue.js/Node.js",
    desc: "Le site web que j'ai créé combine les technologies Vue.js et Node.js, ainsi que la bibliothèque GSAP, afin de fournir une expérience interactive et captivante aux utilisateurs. Inspiré par des sites primés sur Awwwards, il offre aux utilisateurs la possibilité de se connecter et de modifier le contenu du site. L'application utilise Vue.js pour développer une interface utilisateur réactive et conviviale. Grâce à Node.js, elle communique avec un serveur backend pour gérer les fonctionnalités d'authentification et de gestion des contenus modifiables. La bibliothèque GSAP (GreenSock Animation Platform) est utilisée pour créer des animations fluides et attrayantes, permettant de donner vie aux éléments visuels du site. Cela contribue à offrir une expérience utilisateur immersive et dynamique. Les utilisateurs peuvent se connecter à leurs comptes personnels, ce qui leur donne accès à des fonctionnalités spéciales, telles que la modification du contenu du site. Ils peuvent ainsi mettre à jour des textes, des images ou d'autres éléments visuels de manière intuitive et conviviale, sans nécessiter de connaissances techniques avancées. En s'inspirant des sites présents sur Awwwards, le design du site met l'accent sur l'esthétique, l'ergonomie et l'expérience utilisateur. Il vise à susciter l'engagement et à captiver les visiteurs grâce à un design moderne, des transitions fluides et des animations soignées. En résumé, ce site web conçu avec Vue.js, Node.js et GSAP offre aux utilisateurs la possibilité de se connecter, de modifier le contenu du site et de bénéficier d'une expérience interactive et visuellement attrayante. Il allie fonctionnalité et design, inspiré par les meilleures pratiques de l'industrie.",
    title: "CityZen",
    url: "https://cityzen-coiffure.fr",
  },
  {
    id: 4,
    images: [
      { src: "next-music-loginscreen.png" },
      { src: "next-music-homescreen.png" },
      { src: "next-music-homescreen2.png" },
      { src: "next-music-homescreen3.png" },
      { src: "next-music-biblioscreen.png" },
      { src: "next-music-favoritescreen.png" },
    ],
    year: 2022,
    type: "School",
    role: "Front-End",
    desc: "Ce mini projet à été réalisé avec NextJs, un framework ReactJS, Tailwindcss et MaterialUi. Le but était de développer une application de musique, nous nous sommes inspirés d’une maquette Dribbble (Dribbble étant un site où toutes sortes de maquettes y sont répertoriées). ID: WeeSii PASSWORD : 1234",
    title: "NextMusic",
    url: "https://next-music.netlify.app",
  },
  {
    id: 2,
    images: [
      { src: "gsb_login.PNG" },
      { src: "gsb_signup.PNG" },
      { src: "GSB_medoc.png" },
      { src: "gsb_utilisateur.png" },
      { src: "gsb_mobile1.jpg" },
      { src: "gsb_mobile2.jpg" },
      { src: "gsb_mobile3.jpg" },
      { src: "gsb_mobile4.jpg" },
      { src: "gsb_mobile5.jpg" },
      { src: "gsb_mobile6.jpg" },
    ],
    year: 2019,
    type: "School",
    role: "FullStack - Angular/NestJS/Ionic",
    desc: "Galaxy Swiss Bourdin est issu de la fusion entre deux grands du milieu pharmaceutique. La force commerciale de ce laboratoire pharmaceutique est assurée par un travail de conseil et d'information. Les visiteurs médicaux (ou délégués) démarchent les médecins, pharmaciens, infirmières et autres métiers de santé susceptibles de prescrire aux patients les produits du laboratoire. Le besoin ici est alors le suivant : on souhaite harmoniser les frais engendrés par ces visiteurs médiaux via une application web qui sera disponible à ces mêmes personnes et aux comptables qui eux pourront gérer la situation des fiches des visiteurs.",
    title: "Cas GSB",
    url: "https://cas-gsb.netlify.app",
  },
  {
    id: 1,
    images: [
      { src: "formassmat1.png" },
      { src: "formassmat2.png" },
      { src: "formassmat3.png" },
    ],
    year: 2020,
    type: "Infans",
    role: "FullStack - HTML/JS/CSS/PHP",
    desc: "Une refonte complète du site web mon compte, en se concentrant sur les dernières tendances de conception et une expérience utilisateur exceptionnelle pour les utilisateurs de formassmat et e-linguo.",
    title: "Refonte FormAssmat",
    url: "https://infans.fr/",
  },
];
